// <auto-generated />

// Copyright (c) 2021-2022 Yoakke.
// Licensed under the Apache License, Version 2.0.
// Source repository: https://github.com/LanguageDev/Yoakke

using System;

namespace Yoakke.SynKit.Parser.Attributes;

/// <summary>
/// An attribute to mark a field or property as the thing holding onto the token source.
/// </summary>
[AttributeUsage(AttributeTargets.Field | AttributeTargets.Property)]
internal class TokenSourceAttribute : Attribute
{
}
