name: 'Build solution'

on: [pull_request, push]

jobs:
  Solution:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
    - name: Clone the repo
      uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.202'
    - name: Build
      run: |
        dotnet build -c release
    - name: Test
      run: |
        dotnet test
