name: 'Build solution'

on:
  push:
    branches:
      - master
    paths:
      - 'Sources/**'
  pull_request:
    branches:
      - '*'
    paths:
      - 'Sources/**'

jobs:
  Solution:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
    - name: Clone the repo
      uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.202'
    - name: Build
      run: |
        cd Sources
        dotnet build -c release
