name: 'Run tests'

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'Sources/**'
  pull_request:
    branches:
      - '*'
    paths:
      - 'Sources/**'

jobs:
  Solution:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
    - name: Clone the repo
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.425'
    - name: Test
      run: |
        cd Sources
        dotnet test
